os: osx 
osx_image: xcode6.4
language: generic
env:
script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - cargo build && ./target/debug/rustdebug ; ls /Users/travis/Library/Logs/DiagnosticReports ; cat /Users/travis/Library/Logs/DiagnosticReports/*
