os: osx 
osx_image: xcode6.4
language: generic
env:
script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "${HOME}/.cargo/env" && cargo build && ulimit -c unlimited && echo "cores before:" ; ls /cores ; ./target/debug/rustdebug ; echo "cores after:" ; ls /cores ; lldb --core /cores/* --batch --one-line "bt"
