os: osx 
language: generic
env:
script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "${HOME}/.cargo/env" && cargo build && ulimit -c unlimited && ./target/debug/rustdebug ; pid=$? ; lldb --core /cores/core.$pid --batch --one-line "bt"
