os: osx 
osx_image: xcode6.4
language: generic
env:
script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - curl -sSfL https://github.com/mapbox/logbt/archive/v1.6.0.tar.gz | tar --gunzip --extract --strip-components=2 --exclude="*md" --exclude="test*" --directory=.
  - source "${HOME}/.cargo/env" && cargo build && ulimit -c unlimited && ./logbt ./target/debug/rustdebug
